repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.12
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format

  - repo: local
    hooks:
      - id: prettier
        name: Prettier (via npx)
        entry: npx prettier
        language: node
        args: [--write, --print-width=120]
        files: '\.(js|jsx?|ts|tsx|css|scss|less|html|json)$'
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.21.0
    hooks:
      - id: eslint
        args: [--fix]
        files: '\\.(js|jsx|ts|tsx|vue)$'
