# Generated by Django 5.2 on 2025-06-14 09:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_historicaltask_status_alter_task_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="frontend_id",
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
        migrations.AddField(
            model_name="task",
            name="frontend_id",
            field=models.CharField(default=uuid.uuid4, max_length=100),
        ),
    ]
