# Generated by Django 5.2 on 2025-04-21 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_historicalproject_historicaltask'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.task'),
        ),
        migrations.AddField(
            model_name='historicaltask',
            name='recurrence_rule',
            field=models.TextField(blank=True, help_text='RRULE string (RFC-5545).', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_children', to='core.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence_rule',
            field=models.TextField(blank=True, help_text='RRULE string (RFC-5545).', null=True),
        ),
    ]
