# Generated by Django 5.2 on 2025-05-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicaltask_recurrence_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='status',
            field=models.CharField(choices=[('BACKLOG', 'Backlog'), ('BRAINDUMP', 'Brain Dump'), ('IN_PROGRESS', 'On Board'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='BRAINDUMP', help_text='Status of the task.', max_length=20),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('BACKLOG', 'Backlog'), ('BRAINDUMP', 'Brain Dump'), ('IN_PROGRESS', 'On Board'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='BRAINDUMP', help_text='Status of the task.', max_length=20),
        ),
    ]
