# Generated by Django 5.2 on 2025-06-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_historicaltask_frontend_id_task_frontend_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltask",
            name="frontend_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="frontend_id",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
