# Generated by Django 5.2 on 2025-06-23 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_historicaltask_frontend_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecurrenceSeries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recurrence_rule",
                    models.TextField(
                        blank=True, help_text="RRULE string (RFC-5545).", null=True
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="historicaltask",
            name="recurrence_parent",
        ),
        migrations.RemoveField(
            model_name="historicaltask",
            name="recurrence_rule",
        ),
        migrations.RemoveField(
            model_name="task",
            name="recurrence_parent",
        ),
        migrations.RemoveField(
            model_name="task",
            name="recurrence_rule",
        ),
        migrations.AddField(
            model_name="historicaltask",
            name="recurrence_series",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="core.recurrenceseries",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="recurrence_series",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.recurrenceseries",
            ),
        ),
    ]
