# Generated by Django 5.2 on 2025-05-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_historicaltask_status_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltask',
            name='status',
            field=models.CharField(choices=[('BACKLOG', 'Backlog'), ('BRAINDUMP', 'Brain Dump'), ('ON_BOARD', 'On Board'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='BRAINDUMP', help_text='Status of the task.', max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('BACKLOG', 'Backlog'), ('BRAINDUMP', 'Brain Dump'), ('ON_BOARD', 'On Board'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='BRAINDUMP', help_text='Status of the task.', max_length=20),
        ),
    ]
