# Generated by Django 5.2 on 2025-05-05 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_historicaltask_status_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltask',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 5, 2, 13, 25, 49862, tzinfo=datetime.timezone.utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
