# Generated by Django 5.2 on 2025-06-26 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_recurrenceseries_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltask",
            name="column_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="column_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
