# Generated by Django 5.1.6 on 2025-03-31 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_task_options_task_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_at']},
        ),
    ]
