# Generated by Django 5.2 on 2025-06-26 04:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_historicaltask_column_date_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("column_date__isnull", False), ("recurrence_series__isnull", False)
                ),
                fields=("recurrence_series", "column_date"),
                name="unique_task_per_series_per_date",
            ),
        ),
    ]
