# Generated by Django 5.1.6 on 2025-03-31 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
    ]
