# Generated by Django 5.2 on 2025-07-13 14:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_task_unique_task_per_series_per_date"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["start_at", "order"]},
        ),
        migrations.RemoveConstraint(
            model_name="task",
            name="unique_task_per_series_per_date",
        ),
        migrations.RemoveField(
            model_name="historicaltask",
            name="column_date",
        ),
        migrations.RemoveField(
            model_name="task",
            name="column_date",
        ),
    ]
