# Generated by Django 5.1.6 on 2025-04-03 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_task_end_at_task_start_at_task_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='timezone',
        ),
    ]
