# Generated by Django 5.1.6 on 2025-04-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_task_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order', '-updated_at', '-created_at']},
        ),
    ]
