# Generated by Django 5.1.6 on 2025-04-04 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_task_options_remove_task_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['order']},
        ),
    ]
