# Generated by Django 5.1.6 on 2025-04-04 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
