# Generated by Django 5.1.6 on 2025-04-04 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_task_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='last_updated_at',
        ),
    ]
