# Generated by Django 5.2 on 2025-04-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_task_last_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_in_brain_dump',
        ),
        migrations.AddField(
            model_name='task',
            name='column_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
