# Generated by Django 5.2 on 2025-04-09 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_project_task_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='duration',
            new_name='planned_duration',
        ),
    ]
