# Generated by Django 5.2 on 2025-07-19 14:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GitHubCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "access_token",
                    models.CharField(help_text="GitHub access token", max_length=255),
                ),
                ("token_type", models.CharField(default="bearer", max_length=50)),
                (
                    "scope",
                    models.TextField(blank=True, help_text="Granted scopes", null=True),
                ),
                (
                    "github_username",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("github_user_id", models.BigIntegerField(blank=True, null=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Credentials",
                "verbose_name_plural": "GitHub Credentials",
            },
        ),
        migrations.CreateModel(
            name="GitHubSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sync_enabled", models.BooleanField(default=True)),
                (
                    "sync_repositories",
                    models.JSONField(
                        default=list,
                        help_text="List of repository IDs to sync issues from",
                    ),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "sync_only_assigned",
                    models.BooleanField(
                        default=True, help_text="Only sync issues assigned to the user"
                    ),
                ),
                (
                    "sync_only_open",
                    models.BooleanField(
                        default=True, help_text="Only sync open issues"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "GitHub Settings",
                "verbose_name_plural": "GitHub Settings",
            },
        ),
    ]
