# Generated by Django 5.2 on 2025-07-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("google_calendar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="googlecalendarcredentials",
            name="channel_id",
            field=models.CharField(
                blank=True,
                help_text="Active push channel ID",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="googlecalendarcredentials",
            name="last_sync_params",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="googlecalendarcredentials",
            name="next_sync_token",
            field=models.CharField(
                blank=True,
                help_text="Google Calendar sync token for incremental updates",
                max_length=255,
                null=True,
            ),
        ),
    ]
