# Generated by Django 5.2 on 2025-07-16 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("google_calendar", "0002_googlecalendarcredentials_channel_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="googlecalendarcredentials",
            name="channel_id",
        ),
        migrations.RemoveField(
            model_name="googlecalendarcredentials",
            name="last_sync_params",
        ),
        migrations.RemoveField(
            model_name="googlecalendarcredentials",
            name="next_sync_token",
        ),
    ]
