# Generated by Django 5.2 on 2025-07-18 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "google_calendar",
            "0003_remove_googlecalendarcredentials_channel_id_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.JSONField(
                        help_text="OAuth2 token and refresh token information"
                    ),
                ),
                (
                    "calendar_id",
                    models.CharField(
                        blank=True,
                        help_text="Primary Google Calendar ID",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gmail_sync_enabled", models.BooleanField(default=False)),
                (
                    "granted_scopes",
                    models.JSONField(blank=True, default=set, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="google_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Credentials",
                "verbose_name_plural": "Google Credentials",
            },
        ),
        migrations.DeleteModel(
            name="GoogleCalendarCredentials",
        ),
    ]
