# Generated by Django 5.2 on 2025-07-18 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("google_calendar", "0004_googlecredentials_delete_googlecalendarcredentials"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlecredentials",
            name="granted_scopes",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
