# Generated by Django 5.2 on 2025-07-18 14:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("google_calendar", "0005_alter_googlecredentials_granted_scopes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="googlecredentials",
            name="gmail_sync_enabled",
        ),
    ]
